### ISSUE TITLE
`parse_surname_initials': undefined method `match' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-ietf#111]
```
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ietf-1.13.6/lib/relaton_ietf/bibxml_parser.rb:149:in `parse_surname_initials': undefined method `match' for nil:NilClass (NoMethodError)
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ietf-1.13.6/lib/relaton_ietf/bibxml_parser.rb:109:in `full_name'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:232:in `person'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ietf-1.13.6/lib/relaton_ietf/bibxml_parser.rb:53:in `person'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:219:in `block in contributors'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.9/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.9/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.9/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:218:in `map'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:218:in `contributors'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ietf-1.13.6/lib/relaton_ietf/bibxml_parser.rb:49:in `contributors'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:50:in `fetch_rfc'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:146:in `block in concatenate_files'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:142:in `each'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:142:in `reduce'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:142:in `concatenate_files'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:86:in `bibcollection'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:157:in `concatenate_and_write_to_files'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:69:in `build_collection_file'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:32:in `block in generate'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:31:in `chdir'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:31:in `generate'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:24:in `generate'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/commands/site.rb:25:in `generate'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:4[85](https://github.com/metanorma/packed-mn/actions/runs/3422206288/jobs/5700207817#step:10:86):in `start'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli.rb:34:in `start'
	from /__tebako_memfs__/local/metanorma:217:in `<main>'
```

Full log available here https://github.com/metanorma/packed-mn/actions/runs/3422206288/jobs/5700207817#step:10:78

P.S. on Windows there is a bit different error, but looks like root is the same:

<details>
    <summary>relaton_bib/contributor.rb:22:in `initialize': Either formatted address or city and country must be provided (ArgumentError)</summary>

```

C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/contributor.rb:22:in `initialize': Either formatted address or city and country must be provided (ArgumentError)
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:322:in `new'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:322:in `address'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:309:in `contacts'
xxxxx query_pubid(ISO/IEC 10118-3) response_pubid(ISO/IEC 10118-3:2018)
[info]: Building collection file: site-ietf/documents.xml ...
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:234:in `person'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-ietf-1.13.6/lib/relaton_ietf/bibxml_parser.rb:53:in `person'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:219:in `block in contributors'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.9-x64-mingw32/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.9-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.9-x64-mingw32/lib/nokogiri/xml/node_set.rb:233:in `each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:218:in `map'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:218:in `contributors'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-ietf-1.13.6/lib/relaton_ietf/bibxml_parser.rb:49:in `contributors'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-bib-1.13.13/lib/relaton_bib/bibxml_parser.rb:50:in `fetch_rfc'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:146:in `block in concatenate_files'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:142:in `each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:142:in `reduce'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:142:in `concatenate_files'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:86:in `bibcollection'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:157:in `concatenate_and_write_to_files'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/relaton-cli-1.13.0/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:69:in `build_collection_file'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:32:in `block in generate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:31:in `chdir'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:31:in `generate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/site_generator.rb:24:in `generate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli/commands/site.rb:25:in `generate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:4[85](https://github.com/metanorma/packed-mn/actions/runs/3422206285/jobs/5699560413#step:7:86):in `start'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA[96](https://github.com/metanorma/packed-mn/actions/runs/3422206285/jobs/5699560413#step:7:97).tmp/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.6.pre/lib/metanorma/cli.rb:34:in `start'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrDA96.tmp/src/metanorma:217:in `<main>'
```
```

</details>

**Comment by andrew2net** [comment]
Fixed in v 1.13.7

**Comment by CAMOBAP** [comment]
@andrew2net should I report a separate ticket for `lib/relaton_bib/contributor.rb:22:in `initialize': Either formatted address or city and country must be provided (ArgumentError)`?

**Comment by andrew2net** [comment]
@CAMOBAP Ah, sorry I didn't notice the Windows issue.
The log says that a city or country is not provided. We should either drop invalid addresses or relax the restriction. But I wonder why this happens only in Windows.
Could you provide the source document that caused the error?

**Comment by andrew2net** [comment]
@CAMOBAP just, for now, I've updated the BibXML parser to drop addresses if they don't have city and country. Please update the relaton-bib to v 1.13.14.
If you provide a document that causes the ArgumentError then I can investigate what happens.
