### ISSUE TITLE
When the remote server cannot be contacted, do not crash (this applies to all Relaton gems)

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#21]
When the remote server cannot be contacted, do not crash (this applies to all Relaton gems)

This is what happens to Relaton IETF when the server can't be contacted.

@andrew2net please also ensure this fix applies to all Relaton gems. We should throw an appropriate error instead.

```sh
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
SocketError: Failed to open TCP connection to xml2rfc.tools.ietf.org:443 (getaddrinfo: nodename nor servname provided, or not known)
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:609:in `start'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:485:in `get_response'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/relaton-ietf-0.5.2/lib/relaton_ietf/scrapper.rb:39:in `scrape_page'
```

**Comment by ronaldtse** [comment]
To another extent, @opoudjis , if remote reference retrieval fails, Metanorma should not crash but continue the rendering.

**Comment by opoudjis** [comment]
> To another extent, @opoudjis , if remote reference retrieval fails, Metanorma should not crash but continue the rendering.

metanorma-standoc/spec/asciidoctor-standoc/refs_spec.rb:  it "process ISO reference without an Internet connection" do...
