### ISSUE TITLE
relaton-ietf-1.0.0/lib/relaton_ietf/scrapper.rb:312:in `docids': undefined method `sub' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-ietf#36]
https://github.com/metanorma/mn-samples-ietf/runs/674408016?check_suite_focus=true

```
/var/lib/gems/2.5.0/gems/relaton-ietf-1.0.0/lib/relaton_ietf/scrapper.rb:312:in `docids': undefined method `sub' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.5.0/gems/relaton-ietf-1.0.0/lib/relaton_ietf/scrapper.rb:57:in `fetch_rfc'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli/relaton_file.rb:145:in `block in concatenate_files'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli/relaton_file.rb:140:in `map'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli/relaton_file.rb:140:in `concatenate_files'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli/relaton_file.rb:86:in `bibcollection'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli/relaton_file.rb:153:in `concatenate_and_write_to_files'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli/command.rb:34:in `concatenate'
	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/lib/relaton/cli.rb:20:in `start'
	from /var/lib/gems/2.5.0/gems/relaton-cli-1.0.1/exe/relaton:20:in `<top (required)>'
	from /usr/local/bin/relaton:23:in `load'
	from /usr/local/bin/relaton:23:in `<main>'
```

**Comment by ronaldtse** [comment]
Ping @andrew2net

**Comment by andrew2net** [comment]
Fixed it. Please use relaton-ietf v 1.0.1 and relaton-cli v 1.0.2
