### ISSUE TITLE
(URGENT) relaton-ietf fails in mn-samples-ietf

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#38]
Git clone mn-samples-ietf, run `make all`, see error:

```
bundler: failed to load command: relaton (/Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/relaton)
NoMethodError: undefined method `text' for nil:NilClass
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ietf-0.11.1/lib/relaton_ietf/scrapper.rb:271:in `affiliation'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ietf-0.11.1/lib/relaton_ietf/scrapper.rb:198:in `block in persons'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ietf-0.11.1/lib/relaton_ietf/scrapper.rb:195:in `map'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ietf-0.11.1/lib/relaton_ietf/scrapper.rb:195:in `persons'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ietf-0.11.1/lib/relaton_ietf/scrapper.rb:190:in `contributors'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ietf-0.11.1/lib/relaton_ietf/scrapper.rb:63:in `fetch_rfc'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli/relaton_file.rb:145:in `block in concatenate_files'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli/relaton_file.rb:140:in `map'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli/relaton_file.rb:140:in `concatenate_files'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli/relaton_file.rb:86:in `bibcollection'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli/relaton_file.rb:153:in `concatenate_and_write_to_files'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli/command.rb:33:in `concatenate'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/lib/relaton/cli.rb:20:in `start'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-0.8.5/exe/relaton:20:in `<top (required)>'
```

**Comment by andrew2net** [comment]
please use relaton-ietf v 1.1.2

**Comment by ronaldtse** [comment]
@andrew2net can you help rerun mn-samples-ietf to ensure it works there? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse done https://github.com/metanorma/mn-samples-ietf/runs/754171643
